# current version of the key is preshared in the future it will be upgraded .... will get generated by using authentication protocols...
# key will get stored as byted not as the python string....
shared_secret = b"gatewaytothekey2026"


def get_shared_key():
    return shared_secret
